[global]

database_backups_to_keep = 3
new_user_displayname_suffix = "🆕"
allow_announcements_check = true
allow_encryption = true
allow_federation = true
config_reload_signal = true

allow_registration = true
allow_guest_registration = false
log_guest_registrations = true
suspend_on_register = true
yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse = false
registration_token_file = "/etc/continuwuity-registration-tokens.txt"

allow_public_room_directory_over_federation = true
lockdown_public_room_directory = false
allow_device_name_federation = false
allow_inbound_profile_lookup_federation_requests = false

trusted_servers = [ "matrix.org" ]
query_trusted_key_servers_first = false
query_trusted_key_servers_first_on_join = true
only_query_trusted_key_servers = false

admins_from_room = false
admin_room_notices = true
admin_escape_commands = true
#admin_execute = []
#admin_execute_errors_ignore = true

allow_room_creation = true
block_non_admin_invites = false
allow_unstable_room_versions = true
#default_room_version = "12"

login_via_existing_session = true
auto_join_rooms = []
allow_guests_auto_join_rooms = false
send_messages_from_ignored_users_to_client = false

allow_local_presence = true
allow_incoming_presence = true
allow_outgoing_presence = false
allow_local_read_receipts = true
allow_incoming_read_receipts = true
allow_outgoing_read_receipts = true
allow_local_typing = true
allow_outgoing_typing = true
allow_incoming_typing = true

allow_legacy_media = false
media_startup_check = true
prune_missing_media = false

rocksdb_direct_io = true
rocksdb_max_log_files = 1
rocksdb_compression_algo = "zstd"
rocksdb_recovery_mode = 1
rocksdb_repair = false
rocksdb_stats_level = 1
