use-auth-secret
static-auth-secret=<pwgen -s 64 1>
realm=matrix.domain.tld

min-port=50201
max-port=50299

# WebRTC traffic itself is always encrypted
no-tls
no-dtls

# TLS certificates, including intermediate certs.
# For Let's Encrypt certificates, use `fullchain.pem` here.
# cert=/path/to/fullchain.pem

# TLS private key file
# pkey=/path/to/privkey.pem
